//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.12 at 04:15:02 PM CEST 
//


package org.tmf.dsmapi.troubleTicket.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tmf.dsmapi.troubleTicket.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TroubleTicket_QNAME = new QName("http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", "TroubleTicket");
    private final static QName _RelatedParty_QNAME = new QName("http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", "RelatedParty");
    private final static QName _RelatedObject_QNAME = new QName("http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", "RelatedObject");
    private final static QName _Note_QNAME = new QName("http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", "Note");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tmf.dsmapi.troubleTicket.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RelatedObject }
     * 
     */
    public RelatedObject createRelatedObject() {
        return new RelatedObject();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link RelatedParty }
     * 
     */
    public RelatedParty createRelatedParty() {
        return new RelatedParty();
    }

    /**
     * Create an instance of {@link TroubleTicket }
     * 
     */
    public TroubleTicket createTroubleTicket() {
        return new TroubleTicket();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TroubleTicket }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", name = "TroubleTicket")
    public JAXBElement<TroubleTicket> createTroubleTicket(TroubleTicket value) {
        return new JAXBElement<TroubleTicket>(_TroubleTicket_QNAME, TroubleTicket.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedParty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", name = "RelatedParty")
    public JAXBElement<RelatedParty> createRelatedParty(RelatedParty value) {
        return new JAXBElement<RelatedParty>(_RelatedParty_QNAME, RelatedParty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", name = "RelatedObject")
    public JAXBElement<RelatedObject> createRelatedObject(RelatedObject value) {
        return new JAXBElement<RelatedObject>(_RelatedObject_QNAME, RelatedObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Note }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", name = "Note")
    public JAXBElement<Note> createNote(Note value) {
        return new JAXBElement<Note>(_Note_QNAME, Note.class, null, value);
    }

}
