//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.12 at 04:15:02 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://orange.com/api/troubleTicketManagement/tmf/v2/model/business", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tmf.dsmapi.troubleTicket.model;
